name: Sync Repo Master

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        
      - name: Set up Git
        run: |
          git config --global user.name 'DatteroMaster'
          git config --global user.email 'dev@dattero.org'

      - name: Push to destination repository
        run: |
          git remote add target https://${{ env.DEST_NAME }}:${{ secrets.MASTER_REPO_PAT }}@github.com/${{ env.DEST_NAME }}/${{ env.REPO_NAME }}.git
          git remote update
          git merge target/main
          git push -u origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.MASTER_REPO_PAT }}
          DEST_NAME: DatteroMaster
          REPO_NAME: zakkini-nextjs
