name: Sync Repo Master

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone destination repository
        env:
          DESTINATION_REPO: https://${{ secrets.MASTER_REPO_PAT }}@github.com/DatteroMaster/zakkini-nextjs.git
          ORIGINAL_REPO_URL: ${{ github.event.repository.url }}
        run: |
          git clone --bare ${{ env.ORIGINAL_REPO_URL }}.git repo_to_sync
          cd repo_to_sync
          git push --mirror ${{ env.DESTINATION_REPO }}

      - name: Clean up
        run: rm -rf repo_to_sync
