name: Sync Repo Master

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Clone destination repository
        env:
          DESTINATION_REPO: https://${{ secrets.MASTER_REPO_PAT }}@github.com/DatteroMaster/zakkini-nextjs.git
          ORIGINAL_REPO_URL: ${{ github.event.repository.url }}
        run: |
          git clone --bare $ORIGINAL_REPO_URL repo_to_sync
          cd repo_to_sync
          git clone $DESTINATION_REPO destination_repo
          cd destination_repo
          
          # Rimuovi i workflow dalla repository clonata
          git rm -r --cached .github/workflows

          # Aggiungi e committa i cambiamenti
          git add .
          git commit -m "Sync repository excluding workflows"

          # Esegui il push alla repository di destinazione
          git push origin main

      - name: Clean up
        run: rm -rf repo_to_sync destination_repo
