name: Sync Repo Master

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        
      - name: Set up Git
        run: |
          git config --global user.name 'DatteroMaster'
          git config --global user.email 'dev@dattero.org'

      - name: Add target repository
        run: |
          git remote add target https://x-access-token:${{ secrets.MASTER_REPO_PAT }}@github.com/DatteroMaster/zakkini-nextjs.git
        
      - name: Push changes to target repository
        run: |
          git push -u target main --force
