name: Sync Repo Master

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        
      - name: Set up Git
        run: |
          git config --global user.name 'DatteroMaster'
          git config --global user.email 'dev@dattero.org'

      - name: Push to destination repository
        run: |
          git clone https://${{ env.DEST_NAME }}:${{ secrets.MASTER_REPO_PAT }}@github.com/${{ env.DEST_NAME }}/${{ env.REPO_NAME }}.git
          cd ${{ env.REPO_NAME }}
          git remote add secondary https://${{ env.DEST_NAME }}:${{ secrets.MASTER_REPO_PAT }}@github.com/${{ env.DEST_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          git remote update
          git merge secondary/main
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.MASTER_REPO_PAT }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          DEST_NAME: DatteroMaster
          REPO_NAME: zakkini-nextjs
